export const CHANGE_LOAD_STATUS = 'CHANGE_LOAD_STATUS'
export const CHANGE_MODEL_STATUS = 'CHANGE_MODEL_STATUS'
export const CHANGE_TOAST_STATUS = 'CHANGE_TOAST_STATUS'
export const ADD_TO_CART = 'ADD_TO_CART'

export const SET_COMMENT_ORIGIN = 'SET_COMMENT_ORIGIN'
export const SET_COMMENT_CURRENT = 'SET_COMMENT_CURRENT'
export const SET_BRIDGE = 'SET_BRIDGE'
export const SET_SCROLL_POSITION = 'SET_SCROLL_POSITION'
export const SET_SHARE_SHOW = 'SET_SHARE_SHOW'
export const SET_SHARE_PARAMS_WECHAT = 'SET_SHARE_PARAMS_WECHAT'
export const SET_SHARE_PARAMS_WEIBO = 'SET_SHARE_PARAMS_WEIBO'

export const SET_ANIMATE_LIKE = 'SET_ANIMATE_LIKE'
export const SET_ANIMATE_DOWN = 'SET_ANIMATE_DOWN'
export const SET_ANIMATE_SMILE = 'SET_ANIMATE_SMILE'

export const SET_MESSAGE_BADGE = 'SET_MESSAGE_BADGE'
export const SET_MESSAGE_TIMER = 'SET_MESSAGE_TIMER'

export const SET_HOME_REFRESH = 'SET_HOME_REFRESH'




export const SET_USER_INFO = 'SET_USER_INFO'
export const REMOVE_USER_INFO = 'REMOVE_USER_INFO'
